---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: wordpress
  namespace: default
spec:
  interval: 1m
  timeout: 7m
  chart:
    spec:
      chart: wordpress
      version: '20.1.7'
      sourceRef:
        kind: HelmRepository
        name: artifactory
      interval: 1m
  releaseName: wordpress
